services:
  - type: web
    name: video-generation-engine
    env: python
    plan: free
    buildCommand: |
      cd GenServer
      chmod +x build.sh
      ./build.sh
    startCommand: |
      cd GenServer
      gunicorn GenServer.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: GenServer.settings
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    healthCheckPath: /
